# Generated by Django 3.2.25 on 2024-03-26 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20240326_2249'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='capacity',
            new_name='seats',
        ),
    ]
