# Generated by Django 3.2.25 on 2024-03-26 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_rename_capacity_room_seats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='numberroom',
        ),
    ]
