# Generated by Django 3.2.25 on 2024-03-26 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_remove_room_numberroom'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classroom', models.CharField(max_length=100)),
                ('namebooker', models.CharField(max_length=100)),
                ('seatsuse', models.CharField(max_length=100)),
                ('detetime', models.DateTimeField()),
                ('note', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
