# Generated by Django 3.2.25 on 2024-03-26 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_booking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='detetime',
            new_name='datetime',
        ),
    ]
